Add POSIX's apostrophe flag for printf-based funcs
jart/cosmopolitan pull request #1285
Opened 2024-09-08 16:59 UTC by GabrielRavier

POSIX specifies the <apostrophe> flag character for printf as formatting
decimal conversions with the thousands's grouping characters. Given that
cosmopolitan currently has no support for these grouping characters, all
that is required for supporting this flag is to ignore it - and as it is
already used to indicate quoting (for non-decimal conversions), all that
has to be done is to avoid having it be an alias for the <space> flag so
that decimal conversions don't accidentally behave as though the <space>
flag has also been specified whenever the <apostrophe> flag is utilized.

This patch adds this flag, as described above, along with a test for it.

2024-09-09 01:11 UTC, jart requested changes
We do support grouping. You can say `%,d` for `1,000,000`. Could you please change `%'d` so it formats `1'000'000`? Then afterwards we should probably look into importing Musl's localeconv() function so we can access its grouping field. I want the default behavior for Cosmopolitan Libc to be using that apostrophe since it's culture agnostic and I have a disability that makes me allergic to calling setlocale() and unable to read large numbers without grouping. Obviously though if the locale actually specifies a grouping (e.g. English, German) then we should use what it specifies. If you decide to do this (I will if you won't) then please take care to ensure that obtaining the current locale grouping doesn't link any locale code. It should only need to access a global variable through TLS I think.

2024-09-10 14:09 UTC, GabrielRavier commented
Well, given that in the C/POSIX locale (the mandatory default before `setlocale` is ever called) the thousands grouping character is nothing (as specified in the *LC_NUMERIC in the POSIX Locale* section of the POSIX standard), I'm pretty sure using `'` as the separator without being in the context of an appropriate locale is a completely and utterly non-standard implementation of this flag. I guess I'll implement it like that if you want (when I get the time, so perhaps not today) but I would just like to say that it is 100% a POSIX violation.

2024-09-10 19:52 UTC, GabrielRavier commented
I've added a commit to make this change.

2024-09-11 03:26 UTC, jart commented
I can see that you view this as something important and the standard is on your side. In that case, I'm convinced. Could you please update this PR to go back to the conformant behavior you originally chose?

2024-09-12 14:30 UTC, GabrielRavier commented
I have just done so.

2024-09-15 00:17 UTC, jart approved these changes

2024-09-15 00:17 UTC, merged