Added macro to alias eai2str to gai_strerror
jart/cosmopolitan pull request #131
Opened 2021-03-19 12:50 UTC by fabriziobertocci

Apparently for Linux the correct name of the function to return a string form of the error returned by the `getaddrinfo` is called `gai_strerror` and not `eai2str` (see [man page](https://linux.die.net/man/3/gai_strerror) ).

I have just added a `#define` to alias `eai2str` to `gai_strerror` (since the signature of those functions are the same).

2021-03-20 07:08 UTC, jart requested changes
Thanks for discovering this. Could we just refactor the code to use the standard name?

```
$ grep -R eai2str
tool/build/runit.c:    FATALF("%s:%hu: EAI_%s %m", g_hostname, g_runitdport, eai2str(rc));
tool/net/dig.c:      fprintf(stderr, "getaddrinfo failed: %d (EAI_%s)\n", rc, eai2str(rc));
libc/dns/dns.h:const char *eai2str(int);
libc/dns/eai2str.c:const char *eai2str(int code) {
```

2021-03-20 11:52 UTC, fabriziobertocci commented
oh absolutely, it should be an easy change as I did a grep to see where
that function is being used (there are not that many places)....
Fab

On Sat, Mar 20, 2021 at 3:09 AM Justine Tunney ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for discovering this. Could we just refactor the code to use the
> standard name?
>
> $ grep -R eai2str
> tool/build/runit.c:    FATALF("%s:%hu: EAI_%s %m", g_hostname, g_runitdport, eai2str(rc));
> tool/net/dig.c:      fprintf(stderr, "getaddrinfo failed: %d (EAI_%s)\n", rc, eai2str(rc));
> libc/dns/dns.h:const char *eai2str(int);
> libc/dns/eai2str.c:const char *eai2str(int code) {
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jart/cosmopolitan/pull/131#pullrequestreview-616890466>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5RDSJKQOW6CRUL5XSOLTTTERCY5ANCNFSM4ZOXN2SA>
> .
>

2021-03-21 03:01 UTC, fabriziobertocci commented
ok done, I have also renamed the file `libc/dns/eai2str.c` to `libc/dns/gai_strerror.c` to maintain the same pattern function name = file name.

2021-03-21 03:48 UTC, jart approved these changes
Looks good! Thank you!

2021-03-21 03:48 UTC, merged