Added getnameinfo
jart/cosmopolitan pull request #172
Opened 2021-05-23 11:17 UTC by ahgamut

implementation of getnameinfo is similar to getaddrinfo, with additional internal functions. I tested it with an example program on `1.1.1.1` and `8.8.4.4` and the output matches glibc.

Two helper functions are currently stub:

When performing an rDNS lookup, I have to look through `/etc/hosts` first, but `struct HostsTxt` is already sorted according to *name*. Should I do a linear search or re-sort it according to address (and then sort back)?

The service name is currently mapped to `0` always. I'll try to add a `struct ServicesTxt` similar to `struct HostsTxt` if I figure it out, or just a simple parse of `/etc/services`.

2021-05-24 02:05 UTC, jart requested changes
Thanks for sending this! The /etc/services stuff looks orthogonal to this change. Could we remove that and do it as a separate PR if you need it?

2021-05-24 07:51 UTC, ahgamut commented
Ok, I'll look to add a separate PR for parsing `/etc/services` later (maybe along with the `struct servent` stuff).

What do you think about `ResolveHostsReverse`? Should I implement that in this PR or leave it as a stub?

2021-05-24 18:44 UTC, jart commented
getnameinfo is a reverse lookup function so that other function seems on-topic.

2021-05-24 21:10 UTC, ahgamut commented
Removed the services lookup stub. 

I used the HostsTxt internal structure for the address -> name lookup, so the logarithmic-time lookup of names is lost if one keeps alternating between name and address lookups.

2021-05-24 21:37 UTC, jart commented
We can always make it bidirectional if performance ends up being an issue for someone's use case. Will review as soon as I get a chance.

2021-06-10 02:35 UTC, jart approved these changes
LGTM. Thank you!

2021-06-10 02:35 UTC, merged

2021-06-10 15:20 UTC, ahgamut commented
I tested getnameinfo on the system glibc and looks like it performs a linear lookup: if I have multiple entries with the same IP, glibc picks the first one that matches, but this implementation picks a different one because it starts at the middle.

2021-06-10 17:51 UTC, jart commented
You'd have to replace `qsort` with a stable sorting algorithm and then replace `bsearch` with the leftmost variant of binary search. I'd recommend doing brute force linear since we're only comparing on uint32 ip addresses.

2021-06-12 09:37 UTC, ahgamut commented
I'll submit a PR that uses just brute-force linear search for `ResolveHostsReverse`.

Even then, the `getnameinfo` output would differ between glibc and cosmopolitan when there are multiple entries mapped to the same IP address. Consider the below `/etc/hosts` file:

```bash
localhost    127.0.0.1
ahost        127.0.0.1
bhost        127.0.0.1
mhost        127.0.0.1
xhost        127.0.0.1
yhost        127.0.0.1
zhost        127.0.0.1
```

Now if I call `getnameinfo` to find the result for `127.0.0.1`, `localhost` is the expected return value, but I will get either `ahost` or `mhost` (depending on where the search starts) because `SortHostsTxt` has sorted the entries by name, and `localhost` is no longer first.