check existence of IFNAMSIZ
jart/cosmopolitan pull request #672
Opened 2022-10-25 02:51 UTC by ahgamut

IFNAMSIZ is defined in:

- libc/sock/if.h
- libc/sock/struct/ifreq.h

we add a check in the latter to avoid a complaint when using the amalgamated header.

https://github.com/ahgamut/debug-cosmo-example/issues/1

2022-11-02 06:19 UTC, jart requested changes
Thanks for sending this. Could you delete `IFNAMSIZ` from your choice of header instead? So we only have a single definition in the codebase?

2022-11-06 15:20 UTC, ahgamut commented
I removed IFNAMSIZ from `libc/sock/if.h`, which made it an empty header that's `#include`d in exactly one file, so I removed the `libc/sock/if.h` itself.

2022-11-06 15:22 UTC, jart approved these changes

2022-12-25 06:56 UTC, vinodkd commented
FYI, the zip downloadable from https://justine.lol/cosmopolitan/download.html (actual url: https://justine.lol/cosmopolitan/cosmopolitan.zip) still has this issue:
```
In file included from <command-line>:31:
./cosmopolitan.h:28115: warning: "IFNAMSIZ" redefined
28115 | #define IFNAMSIZ    IF_NAMESIZE
      | 
./cosmopolitan.h:28012: note: this is the location of the previous definition
28012 | #define IFNAMSIZ 16
```
 The fix is easy enough locally, just delete line  28115. However, for the first time attempt at using cosmo, it'd be great if the header file in the downloaded zip had this fixed already.

2023-01-02 00:51 UTC, merged