Linux: Add cachestat, fchmodat2 syscalls
jart/cosmopolitan pull request #958
Opened 2023-11-17 09:02 UTC by The-King-of-Toasters

I haven't wired up fchmodat2 yet, as it's pretty fresh and I wasn't sure to put it in with the fchmodat impl or in its own file.

2023-11-18 09:00 UTC, jart requested changes
Thanks for sending this! System calls are cosmo's bread and butter. It's very exciting to see contributions helping improve them.

2023-11-18 09:00 UTC, jart commented on test/libc/calls/cachestat_test.c
> +│ Copyright 2022 Justine Alexandra Roberts Tunney                              │
[optional] This is test code. Feel free to make your mark in this file rather than attributing it to me.

2023-11-18 10:48 UTC, The-King-of-Toasters commented on libc/sysv/syscalls.sh
> +scall	sys_fchmodat2		0xfffffffffffff1c4	0x1c4	globl # no wrapper Linux 6.6+
I wasn't sure if I should use `cosmo_once` for this ala `copy_file_range`.

2023-11-18 19:56 UTC, jart commented on libc/sysv/syscalls.sh
> +scall	sys_fchmodat2		0xfffffffffffff1c4	0x1c4	globl # no wrapper Linux 6.6+
I'm not terribly concerned about the performance of `fchmodat`.

2023-11-19 12:01 UTC, The-King-of-Toasters commented
I tried adding `cachestat` to `kPledgeStdio`, but I kept getting ENOSYS errors. Might be worth following up yourself.

2023-11-20 03:01 UTC, jart approved these changes
Looks good. Thank you!

2023-11-20 03:01 UTC, merged